### ISSUE TITLE
Contract Support

### ISSUE THREAD

**Issue by hemeac** [hemeac/kiwiTechTree#10]
Custom contracts are likely to be helpful to promote progress.  This will need enough playtime with the tech tree in order to know what are some interesting elements to incorporate from existing contract packs and where existing contract packs are lacking.

**Comment by Clamp-o-Tron** [comment]
I'm on board with this. Once BDB is at least laid out onto the tech tree I'll start brainstorming contracts that would fit. I think, especially with the aviation-and-sounding-rockets-first nature of the tree some contracts like RP-1's altitude, downrange, and supersonic contracts would be nice. Maybe also some contracts for polar-orbiting spy birds?

**Comment by hemeac** [comment]
Closing this, will just keep all Github conversations on this here: https://github.com/Clamp-o-Tron/KSP-Kiwi-Contracts
