### ISSUE TITLE
I dont seem to get any new build parts, even when researching it

### ISSUE THREAD

**Issue by smothyhoo1** [hemeac/kiwiTechTree#112]
![image](https://user-images.githubusercontent.com/119087406/213844323-83d1d7fa-d8b4-4539-96d0-e37b7d859cbb.png)
It just doesnt appear here, and even after researching it, nothing comes up in the VAB

**Comment by hemeac** [comment]
The tech tree is fairly outdated and not in development. I would recommended checking out one of the other probe first trees.

**Comment by smothyhoo1** [comment]
> Owner

all of the trees seem to be broken, none of them have anything really there lol

**Comment by hemeac** [comment]
If you are using one of the trees that have been updated for one of the 1.12 versions and you don't see parts, you probably either need to subscribe to more parts mods or you've installed the tech tree mod incorrectly.
