### ISSUE TITLE
[Balance] Hydrolox engines upgrade balancing

### ISSUE THREAD

**Issue by T10a** [hemeac/kiwiTechTree#52]
Hello,
After some play testing and reading of the configs, it seems that upgrades to hydrolox engines are a touch..... extreme (511s on the CE10 comes to mind)
While *theoretically* hydrolox can hit those numbers, no IRL engine has really hit those numbers outside of some... wild tripropellants.
I'm *probably* overthinking things and Kerbals are more eager to go maximum overdrive and push performance limits for ordinary propellants well beyond what humans would consider rational, with the added mass and cost being "how to not melt the engines" :stuck_out_tongue: 

You don't have to be entirely realistic ofc, as this ain't RP-1. Just a thought after watching the videos and testing (This tech tree otherwise seems well thought out, looking forward to more messing around in game!)
(source on above numbers: https://thephysicsofspacex.files.wordpress.com/2016/07/isp-upper-limits.pdf)

**Comment by hemeac** [comment]
Thanks for the notes, think you are right, given the base ISP, the 10% upgrade does get it a bit higher than seems reasonable.  Think I will knock down the CryoEngine ISPs a touch and keep the upgraded numbers under 500 s.

**Comment by T10a** [comment]
Suggestions personally would be 10% thrust, 5% ISP at 1.5x cost, 10% mass increase? Weaker upgrades, but the upgrade is still potent enough to be an upgrade depending on the mission. (Methalox upgrade multipliers could also be between the percentages of HLOX and KLOX to be an inbetween sort of thing?)

**Comment by hemeac** [comment]
I think for the time being, I will leave those as the default, but I think I can balance that by adding a global config that would allow the user to specify the multipliers that they want for the upgrades and have those multipliers be specified separately for Kerolox, Hydrolox, and Methalox.

**Comment by hemeac** [comment]
I've implemented a system in which the engine upgrade values can be specified by users, but will change the defaults if there is a general consensus that the values for hydrolox should be lower.  Really appreciate the feedback, you helped spur a much better system than would have otherwise existed.
