### ISSUE TITLE
CommnetAntennasExtension support

### ISSUE THREAD

**Issue by yalov** [hemeac/kiwiTechTree#66]
https://forum.kerbalspaceprogram.com/index.php?/topic/177292-*

I have used there the same idea, that I had used for the default TechTree:
I put some antennas not in the Antennas brunch (too many antennas in the same node), but in the neighbor Probe brunch with the lag.
So C3+ Relay in the Probe 8, because stock C4 Relay in the Antenna 8, so user chooses: Antenna 8 node gives more powerful antennas, and Probe 8 gives Probes and less powerful antennas.
Same with the  C4+ Relay, and since there is no Probe 10, the C5+ goes to Antenna 10.

```
@PART[RTLongAntenna3]:NEEDS[CommNetAntennasExtension] // C2 Communotron EXP-VR-2T
{
    @TechRequired = communicationSatellites // Antenna 5
}

@PART[caeDeployableAntenna]:NEEDS[CommNetAntennasExtension] // C2+ High Gain Antenna HG-32
{
    @TechRequired = communicationSatellites // Antenna 5
}

@PART[RTShortDish2]:NEEDS[CommNetAntennasExtension] // C3+ Relay Antenna RA-7
{
	@TechRequired = largeUnmanned // Probes 8
}

@PART[RTLongDish2]:NEEDS[CommNetAntennasExtension] // C4+ Relay Antenna RA-25 
{
	@TechRequired = artificialIntelligence // Probes 9
}

@PART[RTGigaDish1]:NEEDS[CommNetAntennasExtension] // C5+ Communotron "Tigger"
{
    @TechRequired = deepSpaceOpticalCommunications  // Antenna 10
}

@PART[RTGigaDish2]:NEEDS[CommNetAntennasExtension] // C5+ RelayTech One
{
	@TechRequired = deepSpaceOpticalCommunications  // Antenna 10
}



```

**Comment by hemeac** [comment]
I've pushed this through to Github and used that as the basis for Remote Tech Redev Antennas support as well.

**Comment by yalov** [comment]
The patches are not for the Remote Tech Redev Antennas, original power and size were different there, and since it is requirement for the CAE, patches for RTRA needs exclude CAE `:NEEDS[RemoteTechRedevAntennas&!CommNetAntennasExtension]`

**Comment by hemeac** [comment]
I've set up the config so the remote tech antennas go in the same node regardless of whether CAE is installed.  It is functionally a placeholder config or now and will revisit later as that isn't a high priority mod for me at the moment and I don't use Remote Tech.  If anyone has strong preferences on where Remote Tech Redev Antennas should be in the absence of your mod, I am sure they will get in touch on the forums.

**Comment by yalov** [comment]
As it is now, the `:AFTER[RemoteTech-Antennas]` win the MM battle with the :NEEDS[CommNetAntennasExtension] for the CommNetAntennasExtension mod, so if at some point RemoteTech-Antennas patch changes, it will brake CommNetAntennasExtension support.

a placeholder is ok, but I believe that default nodes fit better to the RemoteTech-Antennas, than nodes that I set set up for another mod, so better leave it as placeholder, but make it .txt, and `:NEEDS[RemoteTech-Antennas&!CommNetAntennasExtension]`

**Comment by hemeac** [comment]
I've disabled the RemoteTech Antennas patch for now and will review it later.
