### ISSUE TITLE
Swivel sea level performance

### ISSUE THREAD

**Issue by antilochus00** [hemeac/kiwiTechTree#73]
https://github.com/hemeac/kiwiTechTree/blob/be7e8f3548dba8f626755e61b328b0682f50a5f3/GameData/KiwiTechTree/Configurations/Core/Main.cfg#L1317-L1328

Is this deep of a nerf intentional for the swivel? 85s ISP at sea level seems way off relative to the non-gimballed engine and others in similar position in tree.

**Comment by hemeac** [comment]
Coming in the next update either later today or tomorrow.
