### ISSUE TITLE
Hydrogen Typo

### ISSUE THREAD

**Issue by Wallum** [hemeac/kiwiTechTree#99]
https://github.com/hemeac/kiwiTechTree/blob/b728a59fcc3d00e8b5625df2993d5716ed52bd4a/GameData/KiwiTechTree/Configurations/Mods/WildBlueIndustries/Mk-33/Mk-33.cfg#L621

Lqd Hyrdogen instead of Lqd Hydrogen

**Comment by hemeac** [comment]
Will be in the next update, thanks
